### ISSUE TITLE
Nuxt

### ISSUE THREAD

**Issue by KerryRitter** [Evertt/vue-typescript-decorators#1]
Any luck getting this working with Nuxt? I see your issues opened on other projects

**Comment by Evertt** [comment]
Yes actually, I've been able to adjust this package in such a way that it's now fully compatible with Nuxt.js. Try it! If you can't get it to work then I'll create another repo for a Nuxt.js template using this package.

**Comment by KerryRitter** [comment]
How did you add TS to the Nuxt build? Kinda lost :)

**Comment by Evertt** [comment]
Whoops, I didn't notice this comment for a few days. So I guess I emailed you that zip for nothing. Oh well.
